window.RELEASE_NOTES = [
  ['1.0.31', 'Nạp dữ liệu streaming có thể hủy, tiến trình hoàn tất chạy riêng, đọc sheet XLSX nhẹ hơn và cải thiện ghép mã chính xác.'],
  ['1.0.30', 'Nạp file theo worker, giới hạn dữ liệu trong RAM, quản lý backup và tăng độ an toàn khi chạy native.'],
  ['1.0.29', 'Cố định Electron và bổ sung kiểm tra native binding cho môi trường đóng gói.'],
  ['1.0.28', 'Bổ sung phục hồi database SQLite hỏng, lưu file lỗi để phục hồi thủ công và tạo database mới an toàn.'],
  ['1.0.27', 'Bản vá ổn định cho phiên bản ứng dụng.'],
  ['1.0.26', 'Chuyển ứng dụng desktop sang SQLite, bổ sung nạp dữ liệu gốc, migration và Update/Restore.'],
  ['1.0.25', 'Bổ sung hướng dẫn khởi chạy lần đầu, rebuild native và kiểm thử quy trình đọc file.'],
  ['1.0.24', 'Cho phép tiếp tục nạp các file hợp lệ khi một file lỗi; parser chạy trong tiến trình riêng và có timeout.'],
  ['1.0.23', 'Giữ số lượng PR còn lại và Note, tách dòng PR trùng, đổi tên nút nạp dữ liệu rõ hơn.'],
  ['1.0.22', 'Đổi trạng thái thiếu nguồn thành Chưa đặt hàng.'],
  ['1.0.21', 'Cho phép mở trực tiếp file Excel vừa xuất.'],
  ['1.0.20', 'Thêm sheet PR vs PO + XGC với số lượng, trạng thái, chênh lệch và mã nguồn.'],
  ['1.0.19', 'Điều chỉnh lại quy tắc xuất trạng thái khi không có dữ liệu nhận hàng.'],
  ['1.0.18', 'Cho phép áp dụng một liên kết mã cũ → mã mới cho nhiều dự án.'],
  ['1.0.17', 'Mở rộng ghép các biến thể mã có hậu tố _GC và hậu tố số.'],
  ['1.0.16', 'Cải thiện đọc dữ liệu Quét Mã, ngày tháng và giữ dòng lỗi để kiểm tra.'],
  ['1.0.15', 'Phân loại mã chưa đặt hàng thành Check lại để người dùng xác nhận.'],
  ['1.0.14', 'Chuẩn hóa ngày Quét Mã và hỗ trợ nhiều bố cục dòng dữ liệu.'],
  ['1.0.13', 'Giữ dòng lỗi và dòng gốc để kiểm tra, đếm đúng dòng có dữ liệu và mở rộng đọc XGC.'],
  ['1.0.12', 'Thêm kiểm tra dữ liệu theo mã, tooltip nguồn, tìm mã tương ứng _GC và phát hiện dòng trùng.'],
  ['1.0.11', 'Thêm báo cáo kiểm tra dữ liệu thật, tìm mã trong file và phân loại Khớp, Chênh lệch, Cần kiểm tra.'],
  ['1.0.10', 'Thêm nguồn Xưởng Gia Công, mapping PO/MKS/PR và đối chiếu mã hậu tố _GC.'],
  ['1.0.9', 'Giữ Note trong báo cáo, cải thiện phát hành và sử dụng thư mục build riêng.'],
  ['1.0.8', 'Mở rộng trạng thái Check lại, Hủy, Tồn và Common.'],
  ['1.0.7', 'Cải thiện trạng thái Người Vận Hành, PO/hạn giao và quy tắc PU check.'],
  ['1.0.6', 'Làm mới logo, bổ sung thông tin PO, hạn giao hàng và quy tắc trách nhiệm trong báo cáo.'],
  ['1.0.5', 'Lưu dữ liệu dài hạn, nạp tăng dần, Clear phiên và hướng dẫn sử dụng bằng hình ảnh.'],
  ['1.0.4', 'Tăng tốc ghép mã, bổ sung Note đổi mã và kiểm tra an toàn bộ cài.'],
  ['1.0.3', 'Thêm logo, phiên bản, Job Code, đổi mã đã duyệt PR và cập nhật tự động.'],
  ['1.0.2', 'Bổ sung quản lý database và thao tác xóa có xác nhận an toàn.'],
  ['1.0.1', 'Thêm cập nhật GitHub, liên kết mã cũ → mã mới và phân loại kết quả.'],
  ['1.0.0', 'Phiên bản đầu tiên hỗ trợ nạp dữ liệu, đối chiếu số lượng, ghép mã và xuất Excel.']
].map(([version, summary]) => ({ version, summary }));